#!/usr/bin/env python3
"""
Zenvora Autonomous Engine - Configuration Bridge & Parser
Wraps Microsoft UFO & OpenClaw configuration schemas.
Dynamically syncs environment keys (.env, admin settings) into config/ufo/agents.yaml.
"""

import os
import sys
from pathlib import Path

# Resolve base directories
APP_ROOT = Path(__file__).resolve().parent.parent
CONFIG_UFO_DIR = APP_ROOT / "ufo_config" / "ufo"

def get_env_credentials() -> dict:
    """Read credentials from environment or .env file."""
    api_key = os.getenv("OPENAI_API_KEY") or os.getenv("GEMINI_API_KEY") or ""
    api_type = "openai"
    api_base = os.getenv("OPENAI_API_BASE") or "https://api.openai.com/v1/chat/completions"
    api_model = os.getenv("OPENAI_MODEL") or "gpt-4o"

    # If Gemini is configured
    if os.getenv("GEMINI_API_KEY") and not os.getenv("OPENAI_API_KEY"):
        api_key = os.getenv("GEMINI_API_KEY")
        # Gemini OpenAI-compatible endpoint
        api_base = "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions"
        api_model = "gemini-2.0-flash"

    # Fallback to reading .env directly if not loaded
    if not api_key:
        env_file = APP_ROOT / ".env"
        if env_file.exists():
            try:
                with open(env_file, "r", encoding="utf-8") as f:
                    for line in f:
                        line = line.strip()
                        if line.startswith("OPENAI_API_KEY="):
                            api_key = line.split("=", 1)[1].strip().strip('"').strip("'")
                        elif line.startswith("GEMINI_API_KEY=") and not api_key:
                            api_key = line.split("=", 1)[1].strip().strip('"').strip("'")
                            api_base = "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions"
                            api_model = "gemini-2.0-flash"
            except Exception:
                pass

    return {
        "api_key": api_key,
        "api_type": api_type,
        "api_base": api_base,
        "api_model": api_model
    }

def sync_ufo_agent_config(credentials: dict = None) -> bool:
    """
    Generates or updates config/ufo/agents.yaml using active credentials.
    Ensures Microsoft UFO HostAgent and AppAgent have real multimodal vision credentials.
    """
    creds = credentials or get_env_credentials()
    api_key = creds.get("api_key") or "sk-YOUR_KEY_HERE"
    api_type = creds.get("api_type") or "openai"
    api_base = creds.get("api_base") or "https://api.openai.com/v1/chat/completions"
    api_model = creds.get("api_model") or "gpt-4o"

    CONFIG_UFO_DIR.mkdir(parents=True, exist_ok=True)
    agents_yaml = CONFIG_UFO_DIR / "agents.yaml"

    content = f"""# Auto-generated by Zenvora Autonomous Engine Configuration Bridge
# Official Microsoft UFO & OpenClaw AgentOS Configuration

HOST_AGENT:
  VISUAL_MODE: True
  REASONING_MODEL: False
  API_TYPE: "{api_type}"
  API_BASE: "{api_base}"
  API_KEY: "{api_key}"
  API_MODEL: "{api_model}"
  PROMPT: "ufo/prompts/share/base/host_agent.yaml"
  EXAMPLE_PROMPT: "ufo/prompts/examples/{{mode}}/host_agent_example.yaml"

APP_AGENT:
  VISUAL_MODE: True
  REASONING_MODEL: False
  API_TYPE: "{api_type}"
  API_BASE: "{api_base}"
  API_KEY: "{api_key}"
  API_MODEL: "{api_model}"
  PROMPT: "ufo/prompts/share/base/app_agent.yaml"
  EXAMPLE_PROMPT: "ufo/prompts/examples/{{mode}}/app_agent_example.yaml"
  EXAMPLE_PROMPT_AS: "ufo/prompts/examples/{{mode}}/app_agent_example_as.yaml"

BACKUP_AGENT:
  VISUAL_MODE: True
  API_TYPE: "{api_type}"
  API_BASE: "{api_base}"
  API_KEY: "{api_key}"
  API_MODEL: "{api_model}"
"""

    try:
        with open(agents_yaml, "w", encoding="utf-8") as f:
            f.write(content)
        return True
    except Exception as e:
        print(f"[Config Bridge Error] Failed to write agents.yaml: {e}", file=sys.stderr)
        return False

if __name__ == "__main__":
    success = sync_ufo_agent_config()
    print(f"UFO Configuration Synchronized: {success}")
